---
title: "Music and movies"
author: "Esther Bakels"
date: "9-2-2021"
output: html_document
---

```{r}
library(tidyverse)
library(spotifyr)
library(ggthemes)
library(ggrepel)
```

```{r}
CM_themes <- get_playlist_audio_features("","6ubQSyY5AOAZOTLaBUFHWD")
CM_soundtrack <- get_playlist_audio_features("","5Lo1O7pS5PWc9z6UuplHyX")
CM_faves <- get_playlist_audio_features("","0QzlUG13KFnSFOqgxeEli2")
```

```{r}
songs <-
  bind_rows(
    CM_themes %>% mutate(category = "B. Theme songs"),
    CM_faves %>% mutate(category = "A. My songs"),
    CM_soundtrack %>% mutate(category = "C. more soundtracks")
  )
```
```{r}
movie_songs <-
  bind_rows(
    CM_themes %>% mutate(category = "B. Theme songs"),
    CM_soundtrack %>% mutate(category = "C. more soundtracks")
  )
```

```{r}
songs %>%
  ggplot(aes(x = category, y = valence)) +
  geom_boxplot() +
  theme_wsj() +
  labs(title = "Valence")
```

```{r}
songs %>%
  ggplot(aes(x = category, y = tempo)) +
  geom_boxplot()+
  theme_wsj()+
  labs(title = "Tempo")+
  geom_text_repel(data = subset(movie_songs, tempo > 200), aes(label = track.name), size=3)
```
```{r}
songs %>%
  ggplot(aes(x = category, y = danceability)) +
  geom_boxplot()+
  theme_wsj()+
  labs(title = "Danceability")
```
```{r}
songs %>%
  ggplot(aes(x = category, y = energy)) +
  geom_violin()+
  theme_wsj()+
  labs(title = "Energy")
```



```{r}
ggplot(songs, aes(valence, danceability, colour = category, alpha = track.popularity)) + 
  geom_point()+
  theme_solarized()+
  labs(title = "Dancebility vs. Valence")
```

```{r}
ggplot(songs, aes(energy, tempo, colour = category, size = track.popularity)) + 
  geom_point()+
  theme_solarized()+
  labs(title = "Tempo vs Energy")
```

```{r}
my_songs_mean <- CM_faves %>%
  summarise(
    mean_tempo_my_songs = mean(tempo)
  )
my_songs_mean
```
```{r}
# Print which theme song is closest to mean tempo of my songs
Themes_tempo <- CM_themes[,"tempo"]
Values <- abs(Themes_tempo-c(my_songs_mean))
Min_value = min(Values)
Index <- which(Values==Min_value)
CM_themes[Index, "track.name"]
```





